#!/bin/bash

echo "🚀 Umami Multi-Domain - Local Testing Setup"
echo ""

echo "Current setup uses umami-dev.athas.mx (development)"
echo "For DNS verification to work, you would need to:"
echo "  1. Have actual DNS CNAME pointing to your VPS"
echo "  2. Or modify /etc/hosts locally"
echo ""
echo "Example /etc/hosts entry:"
echo "  127.0.0.1 test.example.com"
echo ""
echo "Then test domain 'test.example.com' in the UI."
echo ""
echo "For production deployment, see DEPLOYMENT_GUIDE.md"
echo ""
echo "Quick Start Testing:"
echo "  1. Open http://localhost:3000"
echo "  2. Login with: admin / umami"
echo "  3. Navigate to /domains"
echo "  4. Add a domain (e.g., test.example.com)"
echo "  5. See DNS instructions in verify dialog"
echo "  6. Test edit/delete functionality"
echo ""
